MAX_CACHE_PAGES = 100
RECIPIENTS_PREVIEW_COUNT = 6
RECIPIENTS_PER_PAGE = 100
MESSAGES_CHECK_DELAY = 30
MESSAGES_CACHE_DELAY = 60
MESSAGES_CACHE_THREADS = 10
MESSAGES_PER_USER_ML = 100


class MessageFolder:
    INBOX = 'inbox'
    SENT = 'sent'


FOLDER_TYPES = [MessageFolder.INBOX, MessageFolder.SENT]
